# Generated by Django 6.0.2 on 2026-03-03 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='repositories',
            field=models.ManyToManyField(blank=True, related_name='repositories', to='management.repository'),
        ),
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='management.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='management.project'),
        ),
    ]
