# Generated by Django 6.0.2 on 2026-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
