# Generated by Django 6.0.2 on 2026-03-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_event_attendees_event_end_time_event_google_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='GoogleToken',
        ),
    ]
